title: "Lesan's Portfolio"
name: "Lesan"
email: "lesankiptoo@gmail.com"
description: "Lesan's portfolio"
url: "https://LesanKiptoo.github.io" 
baseurl: "" 

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache

author:
  name: "Lesan Kiptoo"
  avatar: "/assets/images/lesanProfile.jpg"
  bio: "Cybersecurity enthusiast focused on network and cloud security."
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "lesankiptoo@gmail.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/LesanKiptoo"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/lesankiptoo"
    - label: "Phone"
      icon: "fas fa-phone"
      url: "tel:+254727919676/254721623808"
  


collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
paginate: 0




