title: "Lesan's Portfolio"
name: "Lesan"
email: "lesan@email.com"
description: "Lesan's portfolio"
url: "https://LesanKiptoo.github.io" 
baseurl: "" 

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache

author:
  name: "Lesan"
  avatar: "/assets/images/lesan_profile_400x400.jpg"
  bio: "Cybersecurity enthusiast focused on network and cloud security."

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single




