title: "Lesan Kiptoo Portfolio"
name: "Lesan"
email: "lesankiptoo@gmail.com"
description: "Lesan's portfolio"
url: "https://LesanKiptoo.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache

author:
  name: "Lesan Kiptoo"
  avatar: "/assets/images/LesanProfile.png"
  bio: "Cybersecurity | Networks | Cloud"
  location: "Kenya"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:lesankiptoo@gmail.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/lesankiptoo"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/lesan-kiptoo"
    - label: "Phone"
      icon: "fas fa-phone"
      url: "tel:+254727919676"



collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single





